name: Pluto Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      template_dir:
        required: false
        type: string
        default: ""
jobs:
  review-k8s-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: install Kubernetes-deploy(render)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install activesupport -v 6.1.6
      - run: gem install kubernetes-deploy
      - name: Set Kubernetes Manifest Path
        run: |
          echo "Environment is ${{ github.event.inputs.environment }}"
          if [ -z "${{ github.event.inputs.template_dir }}" ]
          then
             KUBERNETES_MANIFEST_PATH=config/deploy/${{ github.event.inputs.environment }}
          else
            KUBERNETES_MANIFEST_PATH=${{ github.event.inputs.template_dir }}
          fi      
      - name: Run Pluto to scan K8S Manifest and send a report to OpsLevel
        run: |
          echo $KUBERNETES_MANIFEST_PATH
          kubernetes-render --template-dir $KUBERNETES_MANIFEST_PATH | pluto detect - --target-versions k8s=${{ secrets.TARGET_K8S_VERSION }} --output json | curl -i -s -o /dev/null -w "%{http_code}" -X POST https://app.opslevel.com/integrations/custom_event/${{ secrets.OPSLEVEL_WEBHOOK_SECRET_PLUTO }}?alias=${{ inputs.service_name }} -H 'content-type: application/json' --data-binary @-

