name: Pluto Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      template_dir:
        required: false
        type: string
        default: ""
jobs:
  review-k8s-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@v5.10.3
      - name: Install all-in-one Kubernetes tools in a package.
        uses: yokawasa/action-setup-kube-tools@v0.8.2
        with:
          kubectl: '1.24.3'
      - name: Set Kubernetes Manifest Path
        run: |
          if [ -z "${{ inputs.template_dir }}" ]
          then
            echo "KUBERNETES_MANIFEST_PATH=config/deploy/${{ inputs.environment }}" >> $GITHUB_ENV
          else
            echo "KUBERNETES_MANIFEST_PATH=${{ inputs.template_dir }}" >> $GITHUB_ENV
          fi  
      - name: Run Pluto to scan K8S Manifest and send a report to OpsLevel
        shell: bash
        env:
          UNENCRYPTED_TARGET_VERSION: ${{ secrets.TARGET_K8S_VERSION }}
          UNENCRYPTED_OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL: ${{ secrets.OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL }}
        run: |
          kubectl kustomize $KUBERNETES_MANIFEST_PATH | pluto detect - --target-versions k8s=$UNENCRYPTED_TARGET_VERSION --ignore-deprecations --ignore-removals --output json | curl -i -s -X POST $UNENCRYPTED_OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL?alias=${{ inputs.service_name }} -H 'content-type: application/json' --data-binary @-

